nextcloud:
  version: 21.0.0
  user: www-data
  repo_url: https://download.nextcloud.com/server/releases
  apt_packages:
    - php-imap
    - php-imagick
    - php-redis
    - php-apcu
    - php7.3-xml
    - php7.3-zip
    - php7.3-mbstring
    - php7.3-gd
    - php7.3-ldap
    - php7.3-imap
    - php7.3-json
    - php7.3-curl
    - php7.3-intl
    - php7.3-pgsql
    - php7.3-bz2
    - php7.3-bcmath
    - php7.3-gmp
  composer_packages:
    - ext-redis
    - ext-exif
  directories:
    web: /var/www/nextcloud
    data: /opt/nextcloud
  db:
    name: nextcloud
    host: localhost
    port: 5432
    username: nextcloud
    password: nextcloud
  admin:
    username: dummy
    password: dummy