nextcloud:
  version: 21.0.0
  user: www-data
  repo_url: https://download.nextcloud.com/server/releases
  apt_packages:
    - php-imap
    - php-imagick
    - php-redis
    - php-apcu
    - php7.4-xml
    - php7.4-zip
    - php7.4-mbstring
    - php7.4-gd
    - php7.4-ldap
    - php7.4-imap
    - php7.4-json
    - php7.4-curl
    - php7.4-intl
    - php7.4-pgsql
    - php7.4-bz2
    - php7.4-bcmath
    - php7.4-gmp
  composer_packages:
    - ext-redis
    - ext-exif
  directories:
    web: /var/www/nextcloud
    data: /opt/nextcloud
  db:
    name: nextcloud
    host: localhost
    port: 5432
    username: nextcloud
    password: nextcloud
  admin:
    username: dummy
    password: dummy