nextcloud:
  version: 31.0.9
  user: www-data
  repo_url: https://download.nextcloud.com/server/releases
  apt_packages:
    - php-imap
    - php-imagick
    - php-redis
    - php-apcu
    - php-xml
    - php-zip
    - php-mbstring
    - php-gd
    - php-ldap
    - php-imap
    - php-json
    - php-curl
    - php-intl
    - php-pgsql
    - php-bz2
    - php-bcmath
    - php-gmp
  composer_packages:
    - ext-redis
    - ext-exif
  directories:
    web: /var/www/nextcloud
    data: /opt/nextcloud
  db:
    name: nextcloud
    host: localhost
    port: 5432
    username: nextcloud
    password: nextcloud
  admin:
    username: dummy
    password: dummy