vpn_ip_address: "10.99.0.1"
vpn:
  owner: root
  group: root
  listen_port: 51820
  config_directory: /etc/wireguard
  interface: wg0
  packages:
    - gnupg
    - linux-headers-generic
    - wireguard
    - resolvconf
    - qrencode
  peers:
    iphone_se:
      public_key: ZcjrdNjPmy5fNKZkJKxyCmiP5ZDrndY3EVxICEuxlwc=
      ip_address: "10.99.0.2"
    personal_laptop:
      public_key: cS2libl32f1U9FmWxDa+wkeRg3OZHpyaT8UuTeFY3h0=
      ip_address: "10.99.0.3"
    rpi_rosie:
      public_key: JuGlk6iVLemnIQTd4OafkUmh5woOAbsJxtHvQigsu3c=
      ip_address: "10.99.0.4"
    windows_desktop:
      public_key: tKfu+KXHO5DUmPC9Mq/Jok5Z7ILB4gygp+redBB1rVk=
      ip_address: "10.99.0.5"
    linux_desktop:
      public_key: WHY20vPW4rpp1aAUHWnYNMx9DByCe4vY5TyrXPU0aQY=
      ip_address: "10.99.0.6"
    unknown1:
      public:key: zwvIPGitz3oIvdqd+aKB3mHDoxzjhKv96jAcF0AyjFo=
      ip_address: "10.99.0.7"
    unknown2:
      public_key: tW/PKO8Jx0OruZLI2fVbmI0xT0rlPTd7Uhzq1xclbh8=
      ip_address: "10.99.0.8"
    ipad_10th_gen:
      public_key: iwm7TGYYRI5AjRreTqbIH30TPzaeXaA7QW3g9obp/mg=
      ip_address: "10.99.0.9"
# enable to force regeneration of VPN configuration with public/private keys
vpn_regenerate_config: false
