version: "3.7"
services:
#  adguardhome:
#    image: adguard/adguardhome:v0.96-hotfix
#    volumes:
#      - adguardhome-data:/opt/adguardhome/work
#      - /etc/adguardhome:/opt/adguardhome/conf
#    environment:
#      VIRTUAL_HOST: adguard.nas.home
#      VIRTUAL_PORT: 3000
#    ports:
#      - 53

  emby:
    image: emby/embyserver:4.2.0.24
    volumes:
      - emby-config:/config
      - /mnt/Backup1/Music:/mnt/Music
      - /mnt/Backup1/PersonalMedia:/mnt/Photos
      - /mnt/Backup2/Videos/Movies:/mnt/Movies
      - /mnt/Backup2/Videos/TV:/mnt/TV
      - /mnt/Backup2/Music Videos:/mnt/MusicVideos
    devices:
      - /dev/dri/renderD128
    environment:
      VIRTUAL_HOST: media.nas.home
      VIRTUAL_PORT: 8096
      # UID of sbreatnach, GID of video
      UID: 1000
      GID: 1000
      GIDLIST: 44

  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - proxy-certs:/etc/nginx/certs
    ports:
      # HTTP/HTTPS
      - "80:80"
      - "443:443"

volumes:
  emby-config:
  proxy-certs: