version: "3.7"
services:
  mysql:
    image: mysql:5.7.27
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      core:
        ipv4_address: 10.5.0.10

  rompr:
    image: registry.nas.home/rmprdckr:1.31
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: music.nas.home
      VIRTUAL_PORT: 8080
      NETWORK_ACCESS: internal
    networks:
      core:
        ipv4_address: 10.5.0.11

  snapcast:
    image: registry.nas.home/snapcast:0.15.0
    command:
      - snapserver
      - -s
      - pipe:///data/snapfifo?name=Mopidy&sampleformat=48000:16:2
    volumes:
      - ./snapcast:/data:rw
    restart: unless-stopped
    ports:
      - 1704:1704
      - 1705:1705
    network_mode: host

  mopidy:
    image: registry.nas.home/mopidy:2.2.3
    volumes:
      - mopidy-local:/var/lib/mopidy/local-sqlite
      - mopidy-playlists:/var/lib/mopidy/playlists
      - /mnt/Backup1/Music:/var/lib/mopidy/media
      - ./snapcast:/snapcast:rw
    restart: unless-stopped
    environment:
      - SCROBBLER_USERNAME
      - SCROBBLER_PASSWORD
    network_mode: host

  emby:
    image: emby/embyserver:4.3.0.13
    volumes:
      - emby-config:/config
      - /mnt/Backup1/Music:/mnt/Music
      - /mnt/Backup1/PersonalMedia:/mnt/Photos
      - /mnt/Backup2/Videos/Movies:/mnt/Movies
      - /mnt/Backup2/Videos/TV:/mnt/TV
      - /mnt/Backup2/Music Videos:/mnt/MusicVideos
    restart: unless-stopped
    devices:
      - /dev/dri/renderD128
    environment:
      VIRTUAL_HOST: media.nas.home
      VIRTUAL_PORT: 8096
      # UID of sbreatnach, GID of video
      UID: 1000
      GID: 1000
      GIDLIST: 44
    networks:
      core:
        ipv4_address: 10.5.0.13

  registry:
    image: registry:2.7
    volumes:
      - registry-data:/var/lib/registry
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: registry.nas.home
      VIRTUAL_PORT: 5000
      NETWORK_ACCESS: internal
    networks:
      core:
        ipv4_address: 10.5.0.15

  adguardhome:
    image: adguard/adguardhome:v0.96-hotfix
    volumes:
      - adguardhome-data:/opt/adguardhome/work
      - adguardhome-conf:/opt/adguardhome/conf
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: adguard.nas.home
      VIRTUAL_PORT: 3000
      NETWORK_ACCESS: internal
    networks:
      core:
        ipv4_address: 10.5.0.16

  coredns:
    image: coredns/coredns:1.6.3
    command:
      - -conf
      - /config/Corefile
    volumes:
      - ./coredns:/config
    restart: unless-stopped
    ports:
      - 53:53/udp
    networks:
      core:
        ipv4_address: 10.5.0.17

  transmission:
    image: linuxserver/transmission:2.94-r1-ls28
    environment:
      PUID: ${UID}
      PGID: ${GID}
      TZ: Europe/Lisbon
      VIRTUAL_HOST: transmission.nas.home
      VIRTUAL_PORT: 9091
    volumes:
      - transmission-config:/config
      - ./transmission/settings.json:/config/settings.json
      - /mnt/Media/Torrents:/downloads
    restart: unless-stopped
    ports:
      - 51413:51413
      - 51413:51413/udp
    networks:
      core:
        ipv4_address: 10.5.0.18

  bitwarden:
    image: bitwardenrs/server:1.10.0-alpine
    restart: always
    volumes:
      - bitwarden-data:/data
    ports:
      - 3012:3012
    environment:
      WEBSOCKET_ENABLED: "true" # Required to use websockets
      SIGNUPS_ALLOWED: "true" # set to false to disable signups
      VIRTUAL_HOST: bitwarden.nas.home
      VIRTUAL_PORT: 80
    networks:
      core:
        ipv4_address: 10.5.0.19

  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy:/etc/nginx/vhost.d
      - proxy-certs:/etc/nginx/certs
    restart: unless-stopped
    ports:
      # HTTP/HTTPS
      - "80:80"
      - "443:443"
    networks:
      core:
        ipv4_address: 10.5.0.100

volumes:
  transmission-config:
  adguardhome-data:
  adguardhome-conf:
  registry-data:
  emby-config:
  mopidy-local:
  mopidy-playlists:
  mysql-data:
  proxy-certs:
  bitwarden-data:

networks:
  core:
    ipam:
      config:
        - subnet: 10.5.0.0/16