version: "3.7"
services:
  mysql57:
   image: mysql:5.7.26
   volumes:
      - db-mysql:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
   environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=piwigo
      - MYSQL_USER=piwigo
      - MYSQL_PASSWORD

  piwigo:
   image: mathieuruellan/piwigo:release-2.9.4
   environment:
     VIRTUAL_HOST: photos.nas.home
     VIRTUAL_PORT: 80
   volumes:
      - ${PHOTO_DIR}:/var/www/galleries
      - piwigo-local:/var/www/local
      - piwigo-plugins:/var/www/plugins
      - piwigo-themes:/var/www/themes
      - piwigo-cache:/var/www/_data/i
      - piwigo-upload:/var/www/upload
      - piwigo-logs:/var/log/apache2

  lychee:
    image: kolex/lychee:3.2.16
    volumes:
      - lychee-config:/usr/share/nginx/html/data
      - ${PHOTO_DIR}:/usr/share/nginx/html/uploads

  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - proxy-certs:/etc/nginx/certs
    ports:
      # HTTP/HTTPS
      - "80:80"
      - "443:443"

volumes:
  db-mysql:
  piwigo-local:
  piwigo-plugins:
  piwigo-themes:
  piwigo-cache:
  piwigo-upload:
  piwigo-logs:
  proxy-certs: