version: "3.7"
services:
#  adguardhome:
#    image: adguard/adguardhome:v0.96-hotfix
#    volumes:
#      - adguardhome-data:/opt/adguardhome/work
#      - /etc/adguardhome:/opt/adguardhome/conf
#    environment:
#      VIRTUAL_HOST: adguard.nas.home
#      VIRTUAL_PORT: 3000
#    ports:
#      - 53

  mysql:
    image: mysql:5.7.27
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  rompr:
    image: sbreatnach/rmprdckr:1.31
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: rompr.nas.home
      VIRTUAL_PORT: 8080

  icecast:
    image: infiniteproject/icecast
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: icecast.nas.home
      VIRTUAL_PORT: 8000

  mopidy:
    image: wernight/mopidy:latest
    volumes:
      - mopidy-local:/var/lib/mopidy/local
      - mopidy-playlists:/var/lib/mopidy/playlists
      - ./mopidy/mopidy.conf:/config/mopidy.conf
      - /mnt/Backup1/Music:/var/lib/mopidy/media
    restart: unless-stopped
    network_mode: host

  emby:
    image: emby/embyserver:4.2.0.24
    volumes:
      - emby-config:/config
      - /mnt/Backup1/Music:/mnt/Music
      - /mnt/Backup1/PersonalMedia:/mnt/Photos
      - /mnt/Backup2/Videos/Movies:/mnt/Movies
      - /mnt/Backup2/Videos/TV:/mnt/TV
      - /mnt/Backup2/Music Videos:/mnt/MusicVideos
    restart: unless-stopped
    devices:
      - /dev/dri/renderD128
    environment:
      VIRTUAL_HOST: media.nas.home
      VIRTUAL_PORT: 8096
      # UID of sbreatnach, GID of video
      UID: 1000
      GID: 1000
      GIDLIST: 44

  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - proxy-certs:/etc/nginx/certs
    restart: unless-stopped
    ports:
      # HTTP/HTTPS
      - "80:80"
      - "443:443"

volumes:
  emby-config:
  mopidy-local:
  mopidy-playlists:
  mysql-data:
  proxy-certs: