version: "3.7"
services:
  mysql:
    image: mysql:5.7.27
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      core:
        ipv4_address: 10.5.0.10

  rompr:
    image: sbreatnach/rmprdckr:1.31
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: music.nas.home
      VIRTUAL_PORT: 8080
    networks:
      core:
        ipv4_address: 10.5.0.11

  icecast:
    image: infiniteproject/icecast
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: icecast.nas.home
      VIRTUAL_PORT: 8000
    networks:
      core:
        ipv4_address: 10.5.0.12

  mopidy:
    image: sbreatnach/mopidy:2.2.3
    volumes:
      - mopidy-local:/var/lib/mopidy/local-sqlite
      - mopidy-playlists:/var/lib/mopidy/playlists
      - /mnt/Backup1/Music:/var/lib/mopidy/media
    environment:
      - SCROBBLER_USERNAME
      - SCROBBLER_PASSWORD
    restart: unless-stopped
    network_mode: host

  emby:
    image: emby/embyserver:4.2.0.24
    volumes:
      - emby-config:/config
      - /mnt/Backup1/Music:/mnt/Music
      - /mnt/Backup1/PersonalMedia:/mnt/Photos
      - /mnt/Backup2/Videos/Movies:/mnt/Movies
      - /mnt/Backup2/Videos/TV:/mnt/TV
      - /mnt/Backup2/Music Videos:/mnt/MusicVideos
    restart: unless-stopped
    devices:
      - /dev/dri/renderD128
    environment:
      VIRTUAL_HOST: media.nas.home
      VIRTUAL_PORT: 8096
      # UID of sbreatnach, GID of video
      UID: 1000
      GID: 1000
      GIDLIST: 44
    networks:
      core:
        ipv4_address: 10.5.0.13

  registry:
    image: registry:2.7
    volumes:
      - registry-data:/var/lib/registry
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: registry.nas.home
      VIRTUAL_PORT: 5000
    networks:
      core:
        ipv4_address: 10.5.0.15

  adguardhome:
    image: adguard/adguardhome:v0.96-hotfix
    volumes:
      - adguardhome-data:/opt/adguardhome/work
      - adguardhome-conf:/opt/adguardhome/conf
    environment:
      VIRTUAL_HOST: adguard.nas.home
      VIRTUAL_PORT: 3000
    networks:
      core:
        ipv4_address: 10.5.0.16

  coredns:
    image: coredns/coredns:1.6.3
    command:
      - -conf
      - /config/Corefile
    volumes:
      - ./coredns:/config
    ports:
      - 53:53/udp
    networks:
      core:
        ipv4_address: 10.5.0.17

  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy:/etc/nginx/vhost.d
      - proxy-certs:/etc/nginx/certs
    restart: unless-stopped
    ports:
      # HTTP/HTTPS
      - "80:80"
      - "443:443"
    networks:
      core:
        ipv4_address: 10.5.0.100

volumes:
  adguardhome-data:
  adguardhome-conf:
  registry-data:
  emby-config:
  mopidy-local:
  mopidy-playlists:
  mysql-data:
  proxy-certs:

networks:
  core:
    ipam:
      config:
        - subnet: 10.5.0.0/16