---
- name:
  hosts: nas
  roles:
    - role: base
      tags: [base]
    - role: ANXS.hostname
      tags: [hostname]
    - role: Stouts.locale
      tags: [locale]
    - role: geerlingguy.ntp
      tags: [ntp]
    - role: ANXS.build-essential
      tags: [utils]
    - role: weareinteractive.ufw
      tags: [firewall]
    - role: external
      tags: [external]
    - role: dns
      tags: [dns]
    - role: storage
      tags: [storage]
    - role: auth
      tags: [auth]
    - role: nextcloud
      tags: [nextcloud]
    - role: wallabag
      tags: [wallabag]
    - role: email
      tags: [email]
    - role: backup
      tags: [backup]
    - role: media
      tags: [media]
    - role: messaging
      tags: [messaging]
    - role: torrents
      tags: [torrents]
    - role: hardening
      tags: [hardening]
  vars_files:
    - vars/playbook.yml
