---
- name:
  hosts: all
  pre_tasks:
    - name: create resolv-file for dnsmasq
      copy:
        content: |
          nameserver 1.1.1.1
          nameserver 8.8.8.8
        dest: /etc/resolv.dnsmasq
  roles:
    - role: base
      tags: [base]
    - role: ANXS.hostname
      tags: [hostname]
    - role: Stouts.locale
      tags: [locale]
    - role: geerlingguy.ntp
      tags: [ntp]
    - role: ANXS.build-essential
      tags: [utils]
    - role: weareinteractive.ufw
      tags: [firewall]
    - role: oefenweb.dnsmasq
      tags: [dns]
    - role: manala.cron
      tags: [cron]
    - role: geerlingguy.nfs
      tags: [nfs]
    - role: hadret.restic
      tags: [restic]
    - role: nginxinc.nginx
      tags: [web-server]
    - role: nginxinc.nginx_config
      tags: [web-server]
    - role: 0x0i.systemd
      tags: [processes]
  vars_files:
    - vars/playbook.yml
