---
- src: ANXS.utilities
  version: v2.0.1
- src: ANXS.apt
  version: v2.1.0
- src: ANXS.hostname
  version: v2.1.1
- src: ANXS.build-essential
  version: v2.0.0
- src: weareinteractive.ufw
  version: 2.0.1
- src: geerlingguy.ntp
  version: 2.1.0
- src: 0x0i.systemd
  version: v0.3.5
