# Matrix server + bridges to Googlechat, Facebook Messenger, et al
- name: setup repository keys
  apt_key:
    url: https://packages.matrix.org/debian/matrix-org-archive-keyring.gpg
    keyring: /usr/share/keyrings/matrix-org-archive-keyring.gpg
    state: present

- name: setup repositories
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/matrix-org-archive-keyring.gpg] https://packages.matrix.org/debian/ buster main
    state: present
    filename: matrix-org

- name: install messaging packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - matrix-synapse-py3

- name: configure messaging files
  template:
    src: "{{ item.name }}.j2"
    dest: "{{ item.path }}/{{ item.name }}"
    owner: matrix-synapse
    mode: "{{ item.mode|default('644') }}"
  with_items:
    - name: homeserver.yaml
      path: "{{ matrix.directory.conf }}"
    - name: log.yaml
      path: "{{ matrix.directory.conf }}"
    - name: server_name.yaml
      path: "{{ matrix.directory.extraconf }}"
    - name: mautrix-facebook-config.yaml
      path: "{{ matrix.directory.extraconf }}"
    - name: mautrix-facebook-registration.yaml
      path: "{{ matrix.directory.extraconf }}"
    - name: mautrix-googlechat-config.yaml
      path: "{{ matrix.directory.extraconf }}"
    - name: mautrix-googlechat-registration.yaml
      path: "{{ matrix.directory.extraconf }}"
    - name: mautrix-whatsapp-config.yaml
      path: "{{ matrix.directory.extraconf }}"
    - name: mautrix-whatsapp-registration.yaml
      path: "{{ matrix.directory.extraconf }}"
    - name: with_env.sh
      path: "{{ matrix.directory.main }}"

- name: install messaging extras
  pip:
    virtualenv: "{{ matrix.directory.venv }}"
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items:
    - name: mautrix
      version: "0.14.0"

- name: register web client directory
  stat:
    path: /var/www/matrixweb
  register: client_result

- name: Install web client
  when: not client_result.stat.exists or force_install is defined
  block:
    - name: download web client
      unarchive:
        src: https://github.com/vector-im/element-web/releases/download/{{ matrix.web_version }}/element-{{ matrix.web_version }}.tar.gz
        dest: /tmp
        remote_src: true

    - name: move client files to www location
      command:
        cmd: mv /tmp/element-{{ matrix.web_version }} /var/www/matrixweb
        removes: /tmp/element-{{ matrix.web_version }}

    - name: override web client files
      template:
        src: "{{ item.src }}.j2"
        dest: /var/www/matrixweb/{{ item.dest }}
      with_items:
        - src: matrixweb-config.json
          dest: config.json
        - src: matrixweb-index.html
          dest: index.html

- name: create pre-built directories
  file:
    path: "{{ matrix.directory.main }}/{{ item.directory }}"
    state: directory
  when: item.directory is defined
  with_items: "{{ matrix.libraries }}"

- name: install pre-built library binary
  get_url:
    url: "{{ item.binary }}"
    dest: "{{ matrix.directory.main }}/mautrix-whatsapp/{{ item.name }}"
    mode: '0755'
  when: item.binary is defined
  with_items: "{{ matrix.libraries }}"

- name: checkout additional libraries
  git:
    repo: "{{ item.repo }}"
    dest: "{{ matrix.directory.main }}/{{ item.name }}"
    version: "{{ item.version }}"
    force: true
  when: item.repo is defined
  with_items: "{{ matrix.libraries }}"

- name: install additional libraries
  shell:
    chdir: "{{ matrix.directory.main }}/{{ item.name }}"
    cmd: /bin/bash {{ matrix.directory.main }}/with_env.sh python setup.py install
  when: item.repo is defined
  with_items: "{{ matrix.libraries }}"

- name: configure systemd files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - matrix-synapse.service
    - mautrix-googlechat.service
    - mautrix-facebook.service
    - mautrix-whatsapp.service
    - matrix-synapse.target

- name: enable systemd services
  systemd:
    state: started
    enabled: true
    name: "{{ item }}"
  with_items:
    - matrix-synapse
    - mautrix-googlechat
    - mautrix-facebook
    - mautrix-whatsapp
    - matrix-synapse.target