
- name: create/update game users
  user:
    name: "{{ item.username }}"
    shell: "{{ item.shell|default(omit) }}"
    home: "{{ item.home_dir|default(omit) }}"
    group: "{{ item.group|default(omit) }}"
    uid: "{{ item.uid|default(omit) }}"
    append: "{{ item.append|default(omit) }}"
    groups: "{{ item.groups|default(omit) }}"
    system: "{{ item.system|default(False) }}"
  with_items: "{{ games.users }}"

- include: minecraft-official.yml
#- import_tasks: minecraft-spigot.yml
- import_tasks: factorio.yml
