monitoring:
  users:
    monitoring:
      username: monitoring
  directories:
    main:
      path: /opt/monitoring
      owner: monitoring
    prometheus:
      path: /opt/monitoring/prometheus-3.13.0.linux-amd64
      owner: monitoring
    node_exporter:
      path: /opt/monitoring/node_exporter-1.11.1.linux-amd64
      owner: monitoring
    grafana:
      path: /opt/monitoring/grafana-13.1.0
      owner: monitoring
  binary_archives:
    - url: https://github.com/prometheus/prometheus/releases/download/v3.13.0/prometheus-3.13.0.linux-amd64.tar.gz
      dest: /opt/monitoring
    - url: https://github.com/prometheus/node_exporter/releases/download/v1.11.1/node_exporter-1.11.1.linux-amd64.tar.gz
      dest: /opt/monitoring
    - url: https://dl.grafana.com/grafana/release/13.1.0/grafana_13.1.0_28013217238_linux_amd64.tar.gz
      dest: /opt/monitoring
