# Install Restic + cronjobs for music and photo backups
- name: create backup user
  user:
    name: backup
    comment: "Backup user"
    home: /home/backup
    groups:
      - postgres

- name: install backup packages
  apt:
    name: "{{ item.name }}"
  with_items: "{{ backup.apt_packages }}"

- name: download Restic
  get_url:
    url: https://github.com/restic/restic/releases/download/v{{ restic.version }}/restic_{{ restic.version }}_linux_amd64.bz2
    dest: /tmp/restic.bz2

- name: unpack Restic to path
  shell: bzip2 -d -k /tmp/restic.bz2 && 
         chmod 755 /tmp/restic &&
         mv /tmp/restic /usr/bin/restic
         creates=/usr/bin/restic

- name: install credential files
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.dest }}"
    owner: backup
    mode: "{{ item.mode }}"
  with_items:
    - src: env
      dest: /home/backup/.env
      mode: "700"

- name: install cron jobs
  cron:
    user: "{{ item.user|default('backup') }}"
    job: "{{ item.job }}"
    name: "{{ item.name }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    day: "{{ item.day }}"
  with_items: "{{ cronjobs }}"