# Keycloak + any other authentication apparatus
- name: create auth user
  user:
    name: auth
    comment: "Auth user"
    home: /home/auth

- import_tasks: ldap.yml
  tags: [ldap]
- import_tasks: keycloak.yml
  tags: [keycloak]