---
distro_name: bullseye
ufw_rules:
  # HTTP/HTTPS
  - port: 80
    rule: allow
  - port: 443
    rule: allow
  # DNS serving
  - port: 53
    rule: allow
  #####
  # Email server
  # SMTP
  - port: 25
    rule: allow
  # IMAPs
  - port: 993
    rule: allow
  # SMTPS
  - port: 465
    rule: allow
  # Mail Send Agent (MSA) (port for sending mails securely)
  - port: 587
    rule: allow
  # SSH
  - port: 22
    rule: allow
  # anything goes on local loop
  - from_ip: 127.0.0.1/8
    rule: allow
  # NFS - from `rpcinfo -p`
  - port: 111
    rule: allow
  - port: 2049
    rule: allow
  - port: 34668
    rule: allow
  - port: 32764
    rule: allow
  - port: 32768
    rule: allow
  # samba
  - port: 445
    rule: allow
  # matrix federation
  - port: 8448
    rule: allow
  # Minecraft
  - port: 8987
    rule: allow
  # MPD API and web UI
  - port: 6600
    rule: allow
  # Snapserver
  - port: 1780
    rule: allow
  - port: 1705
    rule: allow
  - port: 1704
    rule: allow
  # torrent peering
  - port: 51413
    rule: allow
  # VPN access
  - port: 51820
    rule: allow
  # Factorio dedicated server
  - port: 34197
    rule: allow
domains:
  internal: nas.home
  vpn: nas.vpn
  external: somethinginterestinghere.com
  external_name: somethinginterestinghere
  external_tld: com
vpn_ip_address: "10.99.0.1"
root_ip_address: 192.168.1.102
root_network_interface: eno1
vpn_network_interface: wg0
force_install: false
dns:
  fixed_network_addresses:
    # RPi3 in black case
    rosie:
      internal: 192.168.1.106
      vpn: 10.99.0.4
    # Home Assistant RPi3
    hass:
      internal: 192.168.1.183
nfs_exports: []
