---
ufw_rules:
  # HTTP/HTTPS
  - port: 80
    rule: allow
  - port: 443
    rule: allow
  # DNS serving
  - port: 53
    rule: allow
  #####
  # Email server
  # SMTP
  - port: 25
    rule: allow
  # IMAPs
  - port: 993
    rule: allow
  # SMTPS
  - port: 465
    rule: allow
  # Mail Send Agent (MSA) (port for sending mails securely)
  - port: 587
    rule: allow
  # SSH
  - port: 22
    rule: allow
  # anything goes on local loop
  - from_ip: 127.0.0.1/8
    rule: allow
  # NFS - from `rpcinfo -p`
  - port: 111
    rule: allow
  - port: 2049
    rule: allow
  - port: 34668
    rule: allow
  - port: 32764
    rule: allow
  - port: 32768
    rule: allow
  # samba
  - port: 445
    rule: allow
  # matrix federation
  - port: 8448
    rule: allow
  # Minecraft
  - port: 8987
    rule: allow
  # MPD API and web UI
  - port: 6600
    rule: allow
  # Snapserver
  - port: 1780
    rule: allow
  - port: 1705
    rule: allow
  - port: 1704
    rule: allow
  # torrent peering
  - port: 51413
    rule: allow
domains:
  internal: nas.home
  external: somethinginterestinghere.com
  external_name: somethinginterestinghere
  external_tld: com
root_ip_address: 192.168.0.102
dns:
  fixed_network_addresses:
    # RPi3 in black case
    rosie: 192.168.0.106
    # ancient RPi model B
    joyce: 192.168.0.120
nfs_exports:
  - /mnt/Backup     192.168.0.0/24(rw,fsid=0,insecure,no_subtree_check,async)
  - /mnt/Backup1    192.168.0.0/24(rw,fsid=1,insecure,no_subtree_check,async)
  - /mnt/Backup2    192.168.0.0/24(rw,fsid=2,insecure,no_subtree_check,async)
  - /mnt/Media      192.168.0.0/24(rw,fsid=3,insecure,no_subtree_check,async)