- name: clone searxng repository
  ansible.builtin.git:
    repo: https://github.com/searxng/searxng
    dest: "{{ search.directories.home }}/searxng-src"

- name: install base python dependencies
  ansible.builtin.pip:
    name: "{{ search.pip_packages }}"
    virtualenv: "{{ search.directories.home }}/venv"

- name: install searxng requirements
  ansible.builtin.pip:
    requirements: "{{ search.directories.home }}/searxng-src/requirements.txt"
    virtualenv: "{{ search.directories.home }}/venv"

- name: create templates
  ansible.builtin.template:
    src: "{{ item.name }}.j2"
    dest: "{{ item.dest }}/{{ item.name }}"
  loop:
    - name: settings.yml
      dest: "{{ search.directories.home }}"