- name: create DNS serving user
  user:
    name: dns
    comment: "DNS serving user"
    home: /home/dns

- name: download and extract DNS binaries
  unarchive:
    src: "{{ item }}"
    dest: /home/dns
    remote_src: yes
  with_items: "{{ dns.archives }}"

- name: create DNS configurations
  template:
    src: "{{ item.template }}"
    dest: "{{ item.path }}"
  with_items:
    - template: adguard.yaml.j2
      path: /home/dns/adguard.yaml
    - template: Corefile.j2
      path: /home/dns/Corefile
    - template: nas.db.j2
      path: /home/dns/nas.db

- name: set filesystem permissions
  shell: chown -R dns:dns /home/dns

- name: create systemd services
  template:
    src: "{{ item.template }}"
    dest: "{{ item.path }}"
  with_items:
    - template: adguard.service.j2
      path: /etc/systemd/system/adguardhome.service
    - template: coredns.service.j2
      path: /etc/systemd/system/coredns.service

- name: enable systemd services
  systemd:
    state: started
    enabled: true
    name: "{{ item }}"
  with_items:
    - coredns
    - adguardhome