- name: install required packages
  apt:
    name: "{{ email.apt_packages }}"
    state: present

- name: generate TLS certs
  shell: update-ca-certificates

- name: create/update system groups
  group:
    name: "{{ item.name }}"
    system: "{{ item.system|default(False) }}"
  with_items:
    - name: "{{ email.stalwart.username }}"

- name: create/update system users
  user:
    name: "{{ item.username }}"
    home: "{{ item.home_dir|default(omit) }}"
    group: "{{ item.group|default(omit) }}"
    uid: "{{ item.uid|default(omit) }}"
    append: "{{ item.append|default(omit) }}"
    groups: "{{ item.groups|default(omit) }}"
    system: "{{ item.system|default(False) }}"
  with_items:
    - username: "{{ email.stalwart.username }}"
      group: "{{ email.stalwart.username }}"

- name: Disable debconf for ClamAV
  ansible.builtin.debconf:
    name: clamav-daemon
    question: clamav-daemon/debconf
    value: "false"
    vtype: select

- name: generate configuration files
  template:
    src: "{{ item.name }}.j2"
    dest: "{{ item.path }}/{{ item.name }}"
    owner: "{{ item.owner|default(omit) }}"
    group: "{{ item.group|default(omit) }}"
    mode: "{{ item.mode|default(omit) }}"
  with_items:
    - name: 00-clamav-unofficial-sigs.conf
      path: /usr/share/clamav-unofficial-sigs/conf.d
    - name: clamd.conf
      path: /etc/clamav
    - name: clamav-daemon.socket
      path: /lib/systemd/system

- name: Reload clamav daemon
  ansible.builtin.systemd_service:
    name: clamav-daemon.socket
    daemon_reload: true
    state: restarted

- import_tasks: stalwart.yml

- name: Create DNS records for email
  community.general.cloudflare_dns:
    zone: "{{ domains.external }}"
    record: "{{ item.record|default(omit) }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    api_token: "{{ cloudflare.token }}"
  with_items: "{{ email.dns_records }}"
