- name: download userli archive
  unarchive:
    src: https://github.com/systemli/userli/releases/download/{{ userli.version }}/userli-{{ userli.version }}.tar.gz
    dest: /var/www
    remote_src: true
    owner: "{{ userli.user }}"
    group: "{{ userli.user }}"
  args:
    creates: /var/www/userli-{{ userli.version }}

- name: create userli directory link
  file:
    src: "{{ userli.directories.web }}-{{ userli.version }}"
    dest: "{{ userli.directories.web }}"
    owner: "{{ userli.user }}"
    group: "{{ userli.user }}"
    state: link

- name: generate configuration files
  template:
    src: "userli{{ item.name }}.j2"
    dest: "{{ item.path }}/{{ item.name }}"
    owner: "{{ item.owner|default(omit) }}"
    group: "{{ item.group|default(omit) }}"
    mode: "{{ item.mode|default(omit) }}"
  with_items:
    - name: ".env.local"
      path: "{{ userli.directories.web }}"
      owner: "{{ userli.user }}"
      group: "{{ userli.user }}"

- name: Initialise userli instance
  become_user: "{{ userli.user }}"
  shell: "{{ item }}"
  with_items:
    # NB: forcing response to true to force a fake idempotency
    - bin/console doctrine:schema:create || true
    - bin/console app:reservednames:import
    - bin/console cache:clear
    - bin/console cache:warmup
  args:
    chdir: "{{ userli.directories.web }}"

- name: configure remedial cron jobs
  cron:
    user: "{{ userli.user }}"
    job: "{{ item.job }}"
    name: "{{ item.name }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    day: "{{ item.day|default(omit) }}"
  with_items:
    - name: userli deleted user purge
      job: "cd {{ userli.directories.web }} && bin/console app:users:remove -q"
      minute: 0
      hour: 5
    - name: userli unlink old redeemed vouchers
      job: "cd {{ userli.directories.web }} && bin/console app:voucher:unlink"
      minute: 5
      hour: 5
    - name: userli unlink old redeemed vouchers
      job: "cd {{ userli.directories.web }} && bin/console app:report:weekly"
      minute: 10
      hour: 5
      day: 1
