# install Nginx, TLS certificates, Let's Encrypt, certbot, etc.
- name: install external packages
  apt: name={{ item }}
       state=present
  with_items: "{{ external.apt_packages }}"

- name: install python packages
  pip: name={{ item }}
       state=present
  with_items: "{{ external.pip_packages }}"

- name: create configuration files
  template:
    src: "{{ item.name }}.j2"
    dest: "{{ item.path }}/{{ item.name }}"
    mode: "{{ item.mode }}"
  with_items:
    - name: cloudflare.ini
      path: /root
      mode: "600"
    - name: dynamic_ip.sh
      path: /root
      mode: "700"
    - name: php.ini
      path: /etc/php/7.3/fpm
      mode: "644"
    - name: nextcloud-common.conf
      path: /etc/nginx/sites-available
      mode: "644"

- name: remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: create site configs
  template:
    src: "{{ item.name }}.conf.j2"
    dest: "/etc/nginx/sites-available/{{ item.name }}.conf"
    mode: 0600
  with_items: "{{ external.sites }}"

- name: enable site configs
  file:
    state: link
    src: "/etc/nginx/sites-available/{{ item.name }}.conf"
    path: "/etc/nginx/sites-enabled/{{ item.name }}.conf"
  with_items: "{{ external.sites }}"

- name: install certbot certificate
  shell: certbot certonly --dns-cloudflare -n
         --agree-tos -m {{ external.notification_email }}
         --dns-cloudflare-credentials /root/cloudflare.ini \
         -d {{ item }}
         creates=/etc/letsencrypt/live/{{ item }}/fullchain.pem
  with_items: "{{ external.certificate_domains }}"

- name: configure certbot cron
  cron:
    user: root
    minute: "0"
    hour: "0,12"
    name: renew certbot
    job: /usr/local/bin/certbot renew -q --post-hook '/usr/bin/systemctl reload nginx'

- name: configure dynamic ip cron
  cron:
    user: root
    minute: "*/11"
    name: update dynamic IP with DNS provider
    job: /root/dynamic_ip.sh