
- name: create user
  user:
    name: "nakd"
    shell: "/bin/bash"
    create_home: "true"

- name: create service directory
  file:
    path: "/opt/nakd"
    owner: "nakd"
    state: directory

- name: checkout library code
  become_user: "nakd"
  git:
    repo: "https://github.com/sbreatnach/nakd.git"
    dest: "/opt/nakd"
    version: "d5d3064e78df660bf5a6d8d283145139ff195dad"
    force: true

- name: install library dependencies
  become_user: "nakd"
  shell:
    chdir: "/opt/nakd"
    cmd: "uv sync --locked"

- name: create service file
  template:
    src: "nakd.service.j2"
    dest: "/lib/systemd/system/nakd.service"

- name: enable service
  systemd:
    state: started
    enabled: true
    name: "nakd"
