wallabag:
  user: www-data
  secret: dummy
  apt_packages:
    - php7.3-mbstring
    - php7.3-xml
    - php7.3-gd
    - php7.3-json
    - php7.3-intl
    - php7.3-bcmath
    - php7.3-curl
    - php7.3-pgsql
    - php7.3-tidy
    - php7.3-json
  directories:
    web: /var/www/wallabag
  repo:
    tag: 2.4.2
    url: https://github.com/wallabag/wallabag.git
