wallabag:
  os_user: www-data
  users:
    shane:
      password: dummy
      email: shane@somethinginterestinghere.com
      super_admin: true
  clean_install: false
  secret: dummy
  apt_packages:
    - php8.4-mbstring
    - php8.4-xml
    - php8.4-gd
    - php8.4-json
    - php8.4-intl
    - php8.4-bcmath
    - php8.4-curl
    - php8.4-pgsql
    - php8.4-tidy
    - php8.4-json
  directories:
    web: /var/www/wallabag
  repo:
    tag: 2.6.14
    url: https://github.com/wallabag/wallabag.git
