games:
  users:
    # games user reserved by Debian for other uses => use unique user
    - username: server-games
      shell: /bin/bash
      home_dir: /home/server-games
  factorio:
    url: https://factorio.com/get-download/stable/headless/linux64
    directory: /home/server-games/factorio
    save_name: nas
    configs:
      - name: factorio.service
        directory: /lib/systemd/system
  minecraft:
    whitelist:
      - uuid: "59495a2e-a030-47ea-871e-6da1825f74b1"
        name: deesno
    spigot:
      version: "1.21.10"
      directory: /home/server-games/minecraft/spigot
      downloads:
        - url: https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          filename: BuildTools.jar
        - url: https://github.com/Tiiffi/mcrcon/releases/download/v0.7.1/mcrcon-0.7.1-linux-x86-64.tar.gz
          filename: mcrcon-0.7.1.tar.gz
      archives:
        - src: mcrcon-0.7.1.tar.gz
          output: mcrcon-0.7.1-linux-x86-64
      copies:
        - src: spigot-1.21.10.jar
          dest: spigot.jar
        - src: mcrcon-0.7.1-linux-x86-64/mcrcon
          dest: mcrcon
          mode: "0755"
      rcon:
        port: 25575
        password: rcon123
      configs:
        - name: minecraft-spigot.service
          directory: /etc/systemd/system
        - name: eula.txt
          directory: /home/server-games/minecraft/spigot
          owner: server-games
          group: server-games
        - name: server.properties
          directory: /home/server-games/minecraft/spigot
          owner: server-games
          group: server-games
        - name: whitelist.json
          directory: /home/server-games/minecraft/spigot
          owner: server-games
          group: server-games
        - name: spigot.yml
          directory: /home/server-games/minecraft/spigot
          owner: server-games
          group: server-games
      download_url:
      port: 8987
    official:
      directory: /home/server-games/minecraft/official
      configs:
        - name: minecraft-official.service
          directory: /etc/systemd/system
        - name: eula.txt
          directory: /home/server-games/minecraft/official
          owner: server-games
          group: server-games
      download_url: https://piston-data.mojang.com/v1/objects/95495a7f485eedd84ce928cef5e223b757d2f764/server.jar
      port: 8987