# Veracrypt, NFS, Samba + fstab config
- name: install apt packages
  apt: name={{ item.name }}{% if item.version is defined %}={{ item.version }}*{% endif %}
       state=present
  with_items: "{{ storage.apt_packages }}"

- name: install deb packages
  apt: deb={{ item.path }} state=present
  with_items: "{{ storage.deb_packages }}"

- name: enable extra disks
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.device }}"
    fstype: "{{ item.filesystem }}"
    opts: "{{ item.flags }}"
    state: present
  when: item.device is defined
  with_items: "{{ partitions }}"

- include: nfs.yml
- include: samba.yml
- include: postgresql.yml