# Veracrypt, NFS, Samba + fstab config
- name: install apt packages
  apt: name={{ item.name }}{% if item.version is defined %}={{ item.version }}*{% endif %}
       state=present
  with_items: "{{ storage.apt_packages }}"

- name: install deb packages
  apt: deb={{ item.path }} state=present
  with_items: "{{ storage.deb_packages }}"

- name: configure NFS exports
  template:
    src: exports.j2
    dest: /etc/exports

- name: configure Samba mounts
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  
- name: enable extra disks
  lineinfile:
    path: /etc/fstab
    regexp: '^{{ item.device }}'
    line: "{{ item.device }}    {{ item.path }} {{ item.filesystem }}   {{ item.flags }}    0   0"
  when: item.device is defined
  with_items: "{{ partitions }}"