# Veracrypt, NFS, Samba + fstab config
- name: setup repository keys
  apt_key:
    url: "{{ item.url }}"
    keyring: "{{ item.keyring }}"
    state: present
  with_items: "{{ storage.apt_keys }}"

- name: setup repositories
  apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.name }}"
    state: present
  with_items: "{{ storage.apt_repositories }}"

- name: install apt packages
  apt: name={{ item.name }}{% if item.version is defined %}={{ item.version }}*{% endif %}
       state=present
  with_items: "{{ storage.apt_packages }}"

- name: install deb packages
  apt: deb={{ item.path }} state=present
  with_items: "{{ storage.deb_packages }}"

- name: checkout additional libraries
  git:
    repo: "{{ item.repo }}"
    dest: "{{ storage.directory.libraries }}/{{ item.name }}"
    version: "{{ item.version }}"
    force: true
  with_items: "{{ storage.libraries }}"

- name: install additional libraries
  shell:
    chdir: "{{ storage.directory.libraries }}/{{ item.name }}"
    cmd: make && make install
  with_items: "{{ storage.libraries }}"

- name: enable extra disks
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.device }}"
    fstype: "{{ item.filesystem }}"
    opts: "{{ item.flags }}"
    state: present
  when: item.device is defined
  with_items: "{{ partitions }}"

- import_tasks: nfs.yml
- import_tasks: samba.yml
- import_tasks: postgresql.yml
- import_tasks: syncthing.yml

- name: configure onedrive systemd for users
  become_user: "{{ item.username }}"
  systemd:
    state: started
    enabled: true
    name: onedrive
    scope: user
  with_items: "{{ users }}"
