- name: configure NFS
  template:
    src: "{{ item.name }}.j2"
    dest: "{{ item.dir }}/{{ item.name }}"
  with_items:
    - name: exports
      dir: /etc
    - name: nfs-common
      dir: /etc/default

- name: configure NFS exports
  template:
    src: exports.j2
    dest: /etc/exports
