---
- name: install base packages
  apt: name={{ item.name }}{% if item.version is defined %}={{ item.version }}*{% endif %}
       state=present
  with_items: "{{ base.packages }}"

- name: create users
  user: name={{ item.username }} comment="{{ item.name }}"
        password={{ item.password|default(defaults.password) }} shell={{ item.shell }}
  with_items: "{{ users }}"

- name: create system users
  user: name={{ item.username }} shell={{ item.shell }}
        home={{ item.home_directory }} system=yes
  with_items: "{{ system_users }}"

- name: create default tmux config for users
  copy: src=tmux.conf dest=/home/{{ item.username }}/.tmux.conf
  with_items: "{{ users }}"

- name: enable sudo access for appropriate users
  template: src=sudoers.j2 dest=/etc/sudoers.d/users

- name: update environment with extra paths
  template: src=environment.j2 dest=/etc/environment

- name: enable backports
  template: src=backports.list.j2 dest=/etc/apt/sources.list.d/backports.list

- name: disable system beep
  copy: src=nobeep.conf dest=/etc/modprobe.d/nobeep.conf

- name: configure sysctl settings
  copy: src=sysctl.conf dest=/etc/sysctl.conf

- name: create base service files
  template:
    src: "{{ item }}.service.j2"
    dest: "/lib/systemd/system/{{ item }}.service"
  with_items: "{{ base.services }}"

- name: enable base services
  systemd:
    state: started
    enabled: true
    name: "{{ item }}"
  with_items: "{{ base.services }}"