---
- name: install base packages
  apt: name={{ item.name }}{% if item.version is defined %}={{ item.version }}*{% endif %}
       state=present
  with_items: "{{ base.packages }}"

- name: create users
  user: name={{ item.username }} comment="{{ item.name }}"
        password={{ item.password|default(defaults.password) }} shell={{ item.shell }}
  with_items: "{{ users }}"

- name: create default tmux config for users
  copy: src=tmux.conf dest=/home/{{ item.username }}/.tmux.conf
  with_items: "{{ users }}"

- name: enable sudo access for appropriate users
  template: src=sudoers.j2 dest=/etc/sudoers.d/users

- name: update environment with extra paths
  template: src=environment.j2 dest=/etc/environment

- name: disable system beep
  copy: src=nobeep.conf dest=/etc/modprobe.d/nobeep.conf

- name: configure sysctl settings
  copy: src=sysctl.conf dest=/etc/sysctl.conf
