restic:
    version: "0.10.0"
    key: dummy
backblaze:
    key_id: dummy
    key: dummy
backup:
    apt_packages:
        - name: exiftool
cronjobs:
  - name: Books Backup
    job: ". /home/backup/.env && /usr/bin/restic -q -r b2:whizz-books backup /mnt/Backup1/Books/"
    minute: 0
    hour: 3
    day: 1
  - name: Music Backup
    job: ". /home/backup/.env && /usr/bin/restic -q -r b2:whizz-music backup /mnt/Backup1/Music/"
    minute: 0
    hour: 4
    day: 1
  - name: Photo Backup
    job: ". /home/backup/.env && /usr/bin/restic -q -r b2:whizz-photos backup /mnt/Backup1/PersonalMedia/"
    minute: 0
    hour: 4
    day: 2
  - name: sbreatnach OneDrive Backup
    job: ". /home/backup/.env && /usr/bin/restic -q -r b2:whizz-onedrive backup /home/sbreatnach/OneDrive/"
    minute: 0
    hour: 4
    day: 3
  - name: Local DB Backup
    user: postgres
    job: "rm -rf /var/lib/postgresql/curbackup && pg_basebackup -D /var/lib/postgresql/curbackup && chmod -R 750 /var/lib/postgresql/curbackup"
    minute: 0
    hour: 2
    day: "*"
  - name: Remote DB Backup
    job: ". /home/backup/.env && /usr/bin/restic -q -r b2:whizz-db backup /var/lib/postgresql/curbackup/"
    minute: 0
    hour: 3
    day: "*"
  - name: Email Server Backup
    job: ". /home/backup/.env && /usr/bin/restic -q -r b2:whizz-mail backup /var/vmail /var/lib/rspamd/dkim"
    minute: 0
    hour: 3
    day: "*"
    user: root