email:
  stalwart:
    username: stalwart
    directory: /opt/stalwart
    download:
      version: "0.14.0"
    webadmin:
      version: "0.1.33"
      checksum: sha256:731d78b4e17861be9b95a94053ca4f76b86ab34fb65a92480f85664accceac3f
    admin_password:
      # password format is hashed based on
      # https://stalw.art/docs/auth/authentication/password
      # Python one-liner to generate from homelab venv:
      # python -c 'import os; from argon2 import PasswordHasher; hasher = PasswordHasher(); print(hasher.hash(os.environ["NEW_PASS"]))'
      fallback: dummy
      master: dummy
  dns_records:
    - type: MX
      value: home.{{ domains.external }}
    - type: TXT
      record: "@"
      value: "v=spf1 mx -all"
    - type: TXT
      record: _dmarc
      # TODO: add RUA/RUF emails to get data on fraud attempts
      value: "v=DMARC1; p=reject; adkim=s; aspf=s"
    - type: TXT
      record: "2021040906._domainkey"
      value: "v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDPBC9rp2vji2eljpFsvMfL7Sz9gqrLu5hDu1Ig62MRh1Mzz5jF7FZEy7leCwlvMU3L1fNXoEr69JNh7rjrHGdfbLljNej6kjbT7l60VscXhAqsVixyN4K7rWq+DIwF5Cft6YiBtyhGSSIfoRqkbtnKxhQho0f4SbmznmrggAnypQIDAQAB"
    # SMTP2GO DNS records for smtp relay
    - type: CNAME
      record: s663679._domainkey
      value: dkim.smtp2go.net
    - type: CNAME
      record: em663679
      value: return.smtp2go.net
  apt_packages:
    - clamav
    - clamav-daemon
    - clamav-unofficial-sigs
    - ca-certificates
  users: {}
gmail:
  relay_host: "[smtp.gmail.com]:587"
  username: dummy
  app_password: dummy
smtp2go:
  relay_host: "mail.smtp2go.com"
  relay_port: 587
  username: smtp2go.somethinginterestinghere.com
  password: dummy