matrix:
    user: matrix-synapse
    web_version: v1.11.55
    directory:
        venv: /opt/venvs/matrix-synapse
        venv_base: /var/lib/matrix-synapse/venv
        main: /var/lib/matrix-synapse
        logs: /var/log/matrix-synapse
        conf: /etc/matrix-synapse
        extraconf: /etc/matrix-synapse/conf.d
    libraries: []
    oidc:
        client_secret: dummy
    macaroon_secret_key: dummy
    form_secret: dummy
    facebook:
        as_token: dummy
        hs_token: dummy
        sender_localpart: dummy
    whatsapp:
        as_token: dummy
        hs_token: dummy
        sender_localpart: dummy